"""Initial schema: stamp existing tables, add alerts and feedback

Revision ID: 0001
Revises: (none)
Create Date: 2026-06-24

This migration handles the mixed state of the database:
- resistance_records and ingestion_log already exist (created by ingestors)
- alerts and feedback are new and need to be created

Strategy:
    upgrade()  — creates alerts and feedback tables only.
                 resistance_records and ingestion_log are left as-is
                 (Alembic will track them via autogenerate from this point).
    downgrade() — drops alerts and feedback tables only.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Alembic revision identifiers
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    """
    Create the alerts and feedback tables.

    resistance_records and ingestion_log are NOT touched here — they were
    created by the ingestors and already contain data. Alembic will track
    them as part of the baseline from this revision forward.
    """

    # ------------------------------------------------------------------
    # Table: alerts
    # The primary intelligence asset. Every alert generated by the
    # autonomous pipeline is permanently recorded here.
    # ------------------------------------------------------------------
    op.create_table(
        "alerts",
        # Identity
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("pipeline_run_id", sa.String(length=100), nullable=True),

        # Triplet
        sa.Column("pathogen_name", sa.String(length=255), nullable=False),
        sa.Column("antibiotic_name", sa.String(length=255), nullable=False),
        sa.Column("antibiotic_class", sa.String(length=255), nullable=True),
        sa.Column("country_iso3", sa.String(length=3), nullable=False),
        sa.Column("region_who", sa.String(length=50), nullable=True),

        # Severity
        sa.Column("severity_score", sa.SmallInteger(), nullable=False),
        sa.Column("severity_tier", sa.String(length=20), nullable=False),

        # Signal
        sa.Column("signal_type", sa.String(length=50), nullable=False),
        sa.Column("current_resistance", sa.Float(), nullable=True),
        sa.Column("forecasted_rate", sa.Float(), nullable=True),
        sa.Column("deviation_magnitude", sa.Float(), nullable=True),
        sa.Column("trend_direction", sa.String(length=20), nullable=True),
        sa.Column("data_year", sa.SmallInteger(), nullable=True),

        # Intelligence content
        sa.Column("stewardship_guidance", sa.Text(), nullable=True),
        sa.Column("evidence_citations", sa.JSON(), nullable=True),

        # Routing
        sa.Column("routing_target", sa.String(length=100), nullable=True),

        # Outcome tracking
        sa.Column("outcome_confirmed", sa.Boolean(), nullable=True),
        sa.Column("outcome_notes", sa.Text(), nullable=True),
        sa.Column(
            "outcome_recorded_at", sa.DateTime(timezone=True), nullable=True
        ),
    )

    # Indexes on alerts
    op.create_index("ix_alerts_created_at", "alerts", ["created_at"])
    op.create_index("ix_alerts_pathogen_name", "alerts", ["pathogen_name"])
    op.create_index("ix_alerts_antibiotic_name", "alerts", ["antibiotic_name"])
    op.create_index("ix_alerts_country_iso3", "alerts", ["country_iso3"])
    op.create_index("ix_alerts_severity_score", "alerts", ["severity_score"])
    op.create_index("ix_alerts_severity_tier", "alerts", ["severity_tier"])
    op.create_index("ix_alerts_pipeline_run_id", "alerts", ["pipeline_run_id"])
    op.create_index(
        "ix_alerts_triplet",
        "alerts",
        ["pathogen_name", "antibiotic_name", "country_iso3"],
    )
    op.create_index(
        "ix_alerts_severity_created",
        "alerts",
        ["severity_tier", "created_at"],
    )
    op.create_index(
        "ix_alerts_country_created",
        "alerts",
        ["country_iso3", "created_at"],
    )

    # ------------------------------------------------------------------
    # Table: feedback
    # Clinician / analyst ratings on alerts.
    # Closes the intelligence loop: alert → response → outcome → learning.
    # ------------------------------------------------------------------
    op.create_table(
        "feedback",
        sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column(
            "alert_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("alerts.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "feedback_type",
            sa.String(length=20),
            nullable=False,
            server_default="clinical",
        ),
        sa.Column("institution_id", sa.String(length=100), nullable=True),
        sa.Column("user_token", sa.String(length=100), nullable=True),

        # The feedback
        sa.Column("feedback_score", sa.SmallInteger(), nullable=False),
        sa.Column("feedback_note", sa.Text(), nullable=True),
        sa.Column("action_taken", sa.String(length=255), nullable=True),

        # Audit
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )

    # Indexes on feedback
    op.create_index("ix_feedback_submitted_at", "feedback", ["submitted_at"])
    op.create_index("ix_feedback_score", "feedback", ["feedback_score"])
    op.create_index(
        "ix_feedback_alert_submitted",
        "feedback",
        ["alert_id", "submitted_at"],
    )


def downgrade() -> None:
    """
    Remove alerts and feedback tables.

    resistance_records and ingestion_log are intentionally NOT touched.
    """
    op.drop_table("feedback")
    op.drop_table("alerts")